import { ChatSettings } from './types';

export const DEFAULT_SETTINGS: ChatSettings = {
  layout: 'android',
  isDarkMode: false,
  networkType: '4G',
  isDualSim: false,
  batteryLevel: 50,
  isCharging: false,
  showBatteryPercentage: true,
  headerIcon: 'none',
  backgroundImage: '',
  chatBackgroundColor: '#efeae2',
  userBubbleColor: '#d9fdd3',
  receiverBubbleColor: '#ffffff',
  textSize: 13,
  uiTextSize: 13,
  hideHeader: false,
  hideFooter: false,
  showPayment: false,
  showChatArrow: true,
  navigationBar: 'none',
  clockTime: '10:04',
  is24Hour: true,
  showDynamicIsland: false,
  enableContextMenu: false,
  watermark: {
    show: false,
    text: 'WA-Palsu',
    position: 'center',
    opacity: 0.3,
    rotation: 0,
    size: 18,
    color: '#000000',
    x: 0,
    y: 0,
  },
  receiverName: 'John Doe',
  receiverStatus: 'Online',
  receiverAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
  isGroup: false,
  groupMembers: 'Member1, Member2',
  groupParticipants: [
    { id: '1', name: 'User A', color: '#ffb300' },
    { id: '2', name: 'User B', color: '#00a884' }
  ]
};
